#!/bin/sh

conf() {
  printf "
  $(c 1 34)$(Name)
  $(c 1 31)󰥱 os   $(c 1 37)$(Os)
  $(c 1 32)󰥱 kr   $(c 1 37)$(Kernel)
  $(c 1 33)󰥱 up   $(c 1 37)$(Uptime)
  $(c 1 34)󰥱 sh   $(c 1 37)$(Shell)
  $(c 1 35)󰥱 wm   $(c 1 37)$(Desktop)
  $(c 1 36)󰥱 mem  $(c 1 37)$(Memory)

  $(c 1 90) $(c 1 31)  $(c 1 32)  $(c 1 33)  $(c 1 34)  $(c 1 35)  $(c 1 36)  $(c 1 37)  $(c 0 0)
  \n"
}
