# Shell variables
# Generated by 'wal'
wallpaper="/home/Phuoc/Wallpapers/kogecha2.jpg"

# Special
background='#0D0B10'
foreground='#EFDFC5'
cursor='#EFDFC5'

# Colors
color0='#1B1923'
color1='#616B80'
color2='#70B3B4'
color3='#4284a7'
color4='#569F54'
color5='#7FB76F'
color6='#f0c674'
color7='#EFDFC5'
color8='#414242'
color9='#808899'
color10='#8CC2C3'
color11='#5D9DBF'
color12='#84BD82'
color13='#9DC891'
color14='#f5d9a2'
color15='#f5ead9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
