#! /bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1

xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep '*.foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep '*.background:'| awk '{print $NF}')
	COL0=$(xrdb -query | grep '*.color0:'| awk '{print $NF}')
	COL1=$(xrdb -query | grep '*.color1:'| awk '{print $NF}')
	COL2=$(xrdb -query | grep '*.color2:'| awk '{print $NF}')
	COL3=$(xrdb -query | grep '*.color3:'| awk '{print $NF}')
	COL4=$(xrdb -query | grep '*.color4:'| awk '{print $NF}')
	COL5=$(xrdb -query | grep '*.color5:'| awk '{print $NF}')
	COL6=$(xrdb -query | grep '*.color6:'| awk '{print $NF}')
	COL7=$(xrdb -query | grep '*.color7:'| awk '{print $NF}')
}
getcolors

# Bspwm config
bspc monitor -d 一 二 三 四 五 六 

bspc config border_width        10 
bspc config window_gap          12

bspc config focused_border_color "$COL4" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$COL4"
bspc config presel_feedback_color "$COL3"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^6' follow=on 
bspc desktop '^6' --layout monocle

bspc rule -a discord desktop='^5' follow=on 
bspc rule -a Thunar desktop='^4' follow=on 

# Startup
killall -9 xsettingsd feh sxhkd dunst double_border picom polybar

sxhkd &
xsettingsd &

~/.fehbg &
pkill double_border; ~/.config/bspwm/scripts/double_border &
~/.config/dunst/dunst_pywal &

gammastep -m randr -P -O 2900 &
polybar &
picom --config ~/.config/picom/picom.conf
